name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        solana-version: ["1.9.12"] # Will use in future to publish new/multiple verisons
        solana-network: ["devnet"] # Will use in future to support preconfigured networkds
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: codedawi/solana:${{ matrix.solana-version }},codedawi/solana:latest
          build-args: |
            SOLANA_VERSION=${{ matrix.solana-version }}
            SOLANA_CLUSTER=${{ matrix.solana-network }}
